[project]
name = "lerobot-plugins"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lerobot>=0.4.1",
]

[tool.uv.workspace]
members = [
    "robots/template",
    "teleoperators/template",
]
