[project]
name = "lerobot_robot_four_mecanum_wheels_car"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gpiozero>=2.0.1",
    "lgpio>=0.2.2.0",
]
