[project]
name = "lerobot-robot-zmq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "zmq>=0.0.0",
]

# [project.scripts]
# lerobot-zmq-host="lerobot_robot_zmq.zmq_host:main"
